const esbuild = require("esbuild");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const check = process.argv.includes("--check");
const watch = process.argv.includes("--watch");

async function build() {
  for (const name of ["options", "popup"]) {
    const options = {
      absWorkingDir: root,
      entryPoints: [`ui/${name}/main.jsx`],
      outfile: `${name}/${name}.js`,
      bundle: true,
      format: "iife",
      jsx: "automatic",
      target: ["chrome110", "firefox140"],
      define: { "process.env.NODE_ENV": '"production"' },
      minify: true,
      legalComments: "eof",
      charset: "utf8",
      banner: {
        js: "// Generated by npm run build. Edit ui/ sources instead.",
      },
    };
    if (watch) {
      const context = await esbuild.context(options);
      await context.watch();
    } else {
      const result = await esbuild.build({ ...options, write: false });
      for (const file of result.outputFiles) {
        if (check) {
          if (
            !fs.existsSync(file.path) ||
            !fs.readFileSync(file.path).equals(Buffer.from(file.contents))
          )
            throw new Error(
              `Stale bundle: ${path.relative(root, file.path)}. Run npm run build.`,
            );
        } else fs.writeFileSync(file.path, file.contents);
      }
    }
  }
  console.log(
    watch
      ? "Watching React UI sources…"
      : check
        ? "UI bundles match their sources."
        : "Built options and popup React UI.",
  );
}
build().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
